### ISSUE TITLE
Add proper description and tags for the repository

### ISSUE THREAD

**Issue by farooqkz** [linkolearn/linkolearn#12]
Salaam to you my old friend!

I just realized you have released 1.0.0 of linkversity. But after opening the repository, I can't find any clue what is this all about. Remember that a software which lacks documentation, will become useless, even possibly for yourself, in near future.

**Comment by Abdur-rahmaanJ** [comment]
Wa alaikum salaam. Super happy to see you. Yes, sorry i missed this one completely. Solved in #17.

Btw can you try contriblearn and report feedback? That would help me much!

**Comment by farooqkz** [comment]
Feedback is possible. However, I don't think I can do any contribution at least in the near future.

**Comment by Abdur-rahmaanJ** [comment]
Don't worry, the feedback is the contrib
